version: '3'

services: 
    server:
        container_name: server
        build: ./server/
        ports: 
            - "8000:8000"
    app:
        container_name: app
        build: ./app/
        ports: 
            - "8080:8080"
        
        
            
        